### ISSUE TITLE
Needs readme rewrite for support for nodejs rewrite

### ISSUE THREAD

**Issue by fredx30** [gudchalmers/chs-mc-website#3]
Readme still describes usage of composer- a php packagemanager tool.
This should likely describe where the js docker image(s) are and how to launch them.

**Comment by C4illin** [comment]
I have written a readme but it isn't pushed to main yet. Is there anything specific you are wondering about?

**Comment by fredx30** [comment]
Nope just happy to see GUD i still popping upp in my newsfeed! :D
Good work!
